name: Stop Bot

on:
  workflow_dispatch:  # Permet aussi le déclenchement manuel
    inputs:
      start_action:
        description: 'Y == start, N == stop'
        required: true
        default: true
        type: boolean

jobs:
  stop_it:
    name: Connect and stop the bot
    runs-on: ubuntu-latest

    steps:
      - name: Stop the bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/bot-forge
            
            if [ "${{ inputs.start_action }}" = "false" ]; then
              echo "Stopping bot..."
              pm2 stop discord-bot
              echo "Bot stopped!"
            else
              echo "Starting bot..."
              pm2 start dist/bot.js --name discord-bot
              echo "Bot started!"
            fi
            pm2 status

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Bot stopped successful!"
          else
            echo "❌ Ohoh, can't stop the bot!"
          fi
