name: Deploy Bot to Linux Server

on:
  workflow_dispatch:  # Permet aussi le déclenchement manuel

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Linux Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/bot-forge
            echo "Stopping bot..."
            pm2 stop discord-bot
            echo "Bot stopped!"
            pm2 status

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Bot stopped successful!"
          else
            echo "❌ Ohoh, can't stop the bot!"
          fi
